name: dakmadad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.15
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  provider: ^6.1.2
  flutter_login: ^5.0.0
  cloud_firestore: ^5.5.0
  edge_detection: ^1.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

  path: any
  firebase_storage: ^12.3.6
  uuid: ^4.5.1
  http: ^1.2.2
  supabase_flutter: ^2.8.1
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  shared_preferences: ^2.3.3
  qr_code_scanner: ^1.0.1
  http_parser: ^4.0.2
  lottie: ^3.1.3
  flutter_localizations:
    sdk: flutter
  intl: any 
  google_nav_bar: ^5.0.7
  web_socket_channel: ^3.0.1
  google_generative_ai: ^0.4.6
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  flutter_gemini: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/icons/
    - assets/jsons/
