// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxONvcaGcMbBvY-RrVcXW8fzX30DqU4jI',
    appId: '1:867503451116:web:f079c45d0670aee672eec9',
    messagingSenderId: '867503451116',
    projectId: 'india-post-cfab4',
    authDomain: 'india-post-cfab4.firebaseapp.com',
    databaseURL: 'https://india-post-cfab4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'india-post-cfab4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVMs_kqa3BpzfYdfk_OGv-HoGj6myHS0',
    appId: '1:867503451116:android:8e72f4da2d3634de72eec9',
    messagingSenderId: '867503451116',
    projectId: 'india-post-cfab4',
    databaseURL: 'https://india-post-cfab4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'india-post-cfab4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxONvcaGcMbBvY-RrVcXW8fzX30DqU4jI',
    appId: '1:867503451116:web:3bccb222666877ee72eec9',
    messagingSenderId: '867503451116',
    projectId: 'india-post-cfab4',
    authDomain: 'india-post-cfab4.firebaseapp.com',
    databaseURL: 'https://india-post-cfab4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'india-post-cfab4.firebasestorage.app',
  );
}
